src/objects/LMS_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Aadhaar_No__c</fullName>
        <label>Aadhaar No</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAN_No__c</fullName>
        <label>PAN No</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PF_Account_Number__c</fullName>
        <label>PF Account Number</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomOBjects.cls
public class CustomOBjects {
    public static void customObjects(){
        //List<LMS_Employee__c> emsList = new List<LMS_Employee__c>();
       // LMS_Employee__c e = new LMS_Employee__c(Name = 'Santhu', PAN_No__c = 'CDSPA1234M',PF_Account_Number__c = 'APHYD0006082000000',Aadhaar_No__c= '860735732506' );
       // LMS_Employee__c e1 = new LMS_Employee__c(Name = 'Master',PAN_No__c = 'ADSPA1234M',PF_Account_Number__c = 'BPHYD0006082000000',Aadhaar_No__c= '360735732506');
        
       // emsList.add(e);
       // emsList.add(e1);
       // insert emsList;
       
        List<LMS_Employee__c> emsList = new List<LMS_Employee__c>();
        List<LMS_Employee__c> Em = [SELECT Id, Name FROM LMS_Employee__c where Name = 'Santhu' ];
        for(LMS_Employee__c E: Em){
            E.Name = 'JaiHind';
            emsList.add(E);
            
                
        }
        system.debug('E');
        Update emsList;
        
    }
    
}